// Alert Reducer
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Reducer
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOADING = 'LOADING';
export const CREATED_UNCONFIRMED_USER = 'CREATED_UNCONFIRMED_USER';
export const USER_UPDATED = 'USER_UPDATED';

// Metrics Reducer
export const SET_METRICS = 'SET_METRICS';
export const CLEAR_METRICS = 'CLEAR_METRICS';
export const METRICS_ERROR = 'METRICS_ERROR';
export const LOADING_METRICS = 'LOADING_METRICS';

// Graph Reducer
export const SET_GRAPH = 'SET_GRAPH';
export const CLEAR_GRAPH = 'CLEAR_GRAPH';
export const GRAPH_ERROR = 'GRAPH_ERROR';
export const LOADING_GRAPH = 'LOADING_GRAPH';

// Receivers Reducer
export const SET_RECEIVERS = 'SET_RECEIVERS';
export const SET_USER_RECEIVER = 'SET_USER_RECEIVER';
export const SET_RECEIVER_DASH_LINK = 'SET_RECEIVER_DASH_LINK';
export const CLEAR_RECEIVERS = 'CLEAR_RECEIVERS';
export const RECEIVERS_ERROR = 'RECEIVERS_ERROR';
export const LOADING_RECEIVERS = 'LOADING_RECEIVERS';

// Plaid Reducer
export const SET_PUBLIC_TOKEN = 'SET_PUBLIC_TOKEN';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const SET_PLAID_TRANSACTIONS = 'SET_PLAID_TRANSACTIONS';
export const SET_PLAID_ITEMS = 'SET_PLAID_ITEMS';
export const CLEAR_PLAID_ITEMS = 'CLEAR_PLAID_ITEMS';
export const PLAID_ERROR = 'PLAID_ERROR';
export const LOADING_PLAID = 'LOADING_PLAID';

// Selected Reducer
export const SET_SELECTED = 'SET_SELECTED';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
export const SELECTED_ERROR = 'SELECTED_ERROR';
export const LOADING_SELECTED = 'LOADING_SELECTED';

// Password Reducer
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
export const LOADING_PASSWORD = 'LOADING_PASSWORD';
export const LOADED_PASSWORD = 'LOADED_PASSWORD';
export const CLEAR_PASSWORD = 'CLEAR_PASSWORD';

// Spending Limit Reducer
export const SET_SPENDING_LIMIT = 'SET_SPENDING_LIMIT';
export const CLEAR_SPENDING_LIMIT = 'CLEAR_SPENDING_LIMIT';
export const SPENDING_LIMIT_ERROR = 'SPENDING_LIMIT_ERROR';
export const SPENDING_LIMIT_SELECTED = 'SPENDING_LIMIT_SELECTED';
export const LOADING_SPENDING_LIMIT = 'LOADING_SPENDING_LIMIT';

// Used for multiple reducers
export const LOGOUT = 'LOGOUT';
